BrauneDigital\CmsBundle\PHPCR\BaseBlock:
    translator: attribute
    referenceable: true
    locale: locale
    fields:
        col:
            type: string
        position:
            type: int
        blockType:
            type: string