braune_digital_cms:
    content_types:
        - {label: 'content_type.headline', name: 'headline'}
        - {label: 'content_type.text', name: 'text'}
        - {label: 'content_type.imagine', name: 'imagine'}

twig:
    form_themes:
        - 'BrauneDigitalCmsBundle:Form:fields.html.twig'

ivory_ck_editor:
    configs:
        braunedigital_cms_default:
            toolbar: [ [ 'Format', 'Styles', 'NumberedList','BulletedList','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], ['Link', 'Unlink'], ['Bold','Italic','Underline','StrikeThrough','-','Undo','Redo'], ["Source", "-"] ]
            format_tags: "h1;h2;h3;div;p"

liip_imagine:
    filter_sets:
        image_upload_thumbnail:
            quality: 90
            filters:
                thumbnail: { size: [150, 100], mode: inset }
        braunedigital_cms_default:
            quality: 90
            filters:
                thumbnail: { size: [150, 100], mode: inset }

cmf_media:
    imagine_filters:
        upload_thumbnail: braunedigital_cms_default
